### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by gabrielmulle** [julionc/dotfiles#2]
Hey dear friend, 
This workaround to prevent Spotify from updating seems to be outdated, just got mine updated to the last version.
It seems that something has changed, I think the update folder is now under Persistent Cache folder .... Any ideas to udpate this? Thanks!!

**Comment by dantebarba** [comment]
+1 ill try to fix it

**Comment by gabrielmulle** [comment]
An update here: so inside PersistentCache folder there's the Update folder containing the update files.
What I did: added those two files Spotify_new.archive and Spotify_new.archive.sig inside this Update folder and also I locked down everything: these files, the update file (.tbz) and also the whole folder.
Some of this actions did it and it is no longer updating.

**Comment by dantebarba** [comment]
Hey @gabrielmulle it didn't work for me. I've found out that Spotify is downloading it's files to sp_update now located in $TMPDIR. This script should work, it scans TEMP and tries to retrieve sp_update, if it's present it will get deleted. Unfortunately setting permissions to 000 doesn't prevent Spotify from updaten, idk how they manage to do that.

https://gist.github.com/iJunkie22/94569f41186df962f272

**Comment by dantebarba** [comment]
Looks like this script is working just OK and its much simpler:

`#!/bin/sh
cd $TMPDIR && mkdir sp_update && chmod 000 $TMPDIR/sp_update`

just schedule it to run at system restart because TMP folder will get cleaned up.
